name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Run Unit Tests
      run: |
        go test -v -race -covermode atomic -coverprofile=covprofile ./...
      
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
      if: always()
      
    - name: Send Coverage to Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
      if: always()

